linters:
  enable:
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - gofmt
    - ineffassign
    - misspell
    - unused

issues:
  # 排除测试文件
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*_test.go"
