version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gocritic
    - gosec
    - revive
    - nilerr
    - exhaustive
    - nolintlint

  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Fprint
        - fmt.Printf
        - fmt.Println
        - fmt.Print
        - (io.Writer).Write

    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
